# -*- coding: utf-8 -*-
"""ex3_0904.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ekxxW3KX1wvabPYo4BB1MZSo98qGffmi
"""

print("Hello World!")

age = 36
txt = f"My name is John, I am {age}"
print(txt)

price = 59
txt2 = f"The price is {price:.2f} dollars"
print(txt2)

txt4 = "banana"
x = txt4.center(20)


print(x)

txt5 = "Hello, welcome to my world."
x = txt5.find("welcome")

print(x)

txt6 = "this is python lecture"

x = txt6.upper()

print(x)

txt7 = "         banana        "
print("of all fruits", txt7, "is my favorite") # txt7 공백이 남아있음
x = txt7.lstrip()  # 왼쪽 공백 자름

print("of all fruits", x, "is my favorite")

x = txt7.rstrip() # 오른쪽 공백 자름
print("of all fruits", x, "is my favorite")

x = txt7.strip() # 양쪽 공백 자름
print("of all fruits", x, "is my favorite")

txt8 = "Hello Sam!"

mytable = str.maketrans("S", "P")  # S 를 P로 바꿔주겠다

print(txt8.translate(mytable))

print(6 ^ 3) # 같은 때는 0 이고 다를 때는 1을 줌  0 0 -> 0  , 1 0 -> 1
print(6 & 3)
print(3 << 2)  # 2진수 비트 숫자를 왼쪽으로 2칸 이동시킴
print(8 >> 2)  # 2진수 비트 숫자를 오른쪽으로 2칸 이동시킴

thisdict = {
    "brand" : "Ford", "model" : "mustang"
}

print(thisdict)

x = thisdict.keys()
print(x)

thisdict["color"] = "white"  # 추가
print(thisdict)

class Myclass():
  x = 5

p1 = Myclass()
print(p1.x)

class Person:
  def __init__(self, name, age):
    self.name = name
    self.age = age

p1 = Person("John", 36)

print(p1.name)
print(p1.age)

class Person:
  def __init__(self, fname, lname):
    self.firstname = fname
    self.lastname = lname

  def printname(self):
    print(self.firstname, self.lastname)

class Student(Person):
  def __init__(self, fname, lname):
    Person.__init__(self, fname, lname)

x = Student("Mike", "Olsen")
x.printname()

import numpy as np

arr = np.array( [1, 2, 3, 4, 5])
arr2 = np.array( (1, 2, 3, 4, 5) )

print(arr)
print(arr2)

print(type(arr))
print(type(arr2))

arr3 = np.array([[1, 2, 3],[4, 5, 6]])  # 행 열

print(arr3)  # 2차원
print(arr3.ndim)

arr4 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]) # 3차원 배열 , 면행열
print(arr4)
print(arr4.ndim)

arr5 = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print("5th element on 2nd row : ",arr5[1,4])

arr6 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

print(arr6[0,1,2])

arr7 = np.array([[1,2,3,4,5],[6,7,8,9,10]])

print("Last element from 2nd dim: ",arr7[1,-1])  # 음수는 뒤에서 시작

arr8 = np.array([1,2,3,4,5,6,7])

print(arr8[1:5])

arr9 = np.array([1,2,3,4,5,6,7])

print(arr9[-3:-1]) # 끝에서 3번째 인덱스부터 1번째 인덱스까지 자릅니다.

arr10 = np.array([1,2,3,4,5,6,7])
print(arr[1:5:2]) # 인덱스 1부터 5까지 각 요소 중 하나씩 건너뛰면서 반환

arr11 = np.array([1,2,3,4,5,6,7])

print(arr[::2]) # 배열 전체에서 한 칸씩 건너뛰면서 요소를 반환

arr12 = np.array([[1,2,3,4,5],[6,7,8,9,10]])

print(arr12 [1, 1:4]) # 두 번째 요소에서 인덱스 1부터 인덱스 4까지의 요소를 잘라냅니다.

arr13 = np.array([[1,2,3,4,5],[6,7,8,9,10]])

print(arr13[0:2 , 2]) #두 요소모두에서 인덱스 2를 반환합니다.

arr14 = np.array([[1,2,3,4,5],[6,7,8,9,10]])

print(arr14[0:2, 1:4]) # 두 요소 모두에서 인덱스 1부터 인덱스 4까지 슬라이스 하면 2차원 배열이 반환됩니다.