# -*- coding: utf-8 -*-
"""ex1_0902.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19X7Uqi107shtXoAdNR1pmq8oeVV1flYF
"""

print("테스트")

print("테스트2")

print('djsjefiosjefoiejofjsie')

print(30)

# 헤헤헤헤헤헤헤헤

x = 5
y = 'john'
print(x)
print(y)

x = str(3)
y = int(3)
z = float(3)

print(x)
print(y)
print(z)

x = "John"
y = 'john'
print(x)
print(y)

x = "Python"
y = "is"
z = "awesome"
print(x, y, z)

print(x + y + z)

x = 5
y = "John"
print(str(x) + y)

def myfunc():
  print("Hello from a function")

myfunc()

def cel(f):
  return (f - 32) * 5 / 9

print(cel(77))
print(cel(95))
print(cel(50))

def cal(f):
  return f + 100

print(cal(100))

from re import MULTILINE
def add(a, b):
  return a + b

def sub(a, b):
  return a - b

def mul(a, b):
  return a * b

def div(a, b):
  return a / b


print(add(10, 20))
print(sub(10, 20))
print(mul(10, 20))
print(div(10, 20))