# -*- coding: utf-8 -*-
"""ex2_0903.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JNuqxffvf6HHMT2Ip_XB9CNWD-eIVw67
"""

x = 5
y = "John"

print(x)
print(type(x))

print(y)
print(type(y))

def myfunc(): # 함수 정의
  global x
  x = "fantastic"

myfunc()

print("Python is " + x)

str = "Hello, World!"
print(len(str))
print()

for x in str:
  print(x,end="")

print()
print("***")

txt = "The best things in life are free!"
print("e are free" in txt)

b = "Hello, World!"
print(b[2:5]) # 2번째 index 부터 5번째 전까지
print(b[:5]) # 0번째 index 부터 5번째 전까지
print(b[2:]) # 2번째 index 부터 끝까지

print(b[-5:-2]) # 음수는 맨 끝부터 숫자세기

a = "Hello World!   "
print(a.upper()) # 대문자 변환
print(a.lower()) # 소문자 변환
print(len(a))

b = a.strip()
print(b) # 문자열 앞 뒤 공백 제거
print(len(b))

a = "Hello World!"
print(a.replace("o","a")) # a의 값을 변경해주는거지 a자체가 변하는건 아님 새로운 변수에 넣어주어야 함

a = "Hello, World!"
print(a.split(",")) # , 기준으로 list 형식으로 나눠줌

class MyClass:
  x = 5

p1 = MyClass()
print(p1.x)

class Person:
  def __init__(self, name, age, tall): # self 는 첫번째에 넣기
    self.name = name
    self.age = age
    self.tall = tall

p1 = Person("홍길동", 36, 180)
p2 = Person("벤자민",23,204)
p3 = Person("세종대황",24,175)


print(p1.name , p1.age , p1.tall)
print(p2.name , p2.age , p2.tall)
print(p3.name , p3.age , p3.tall)

class Person:
    def __init__(self, name, age):
        self.name = name
        self.age = age

    def greet(self):
        print("Hello, my name is " + self.name)
        print("nice " + str(self.age) + " years old")

p1 = Person("Emil", 25)
p1.greet()

class Car:
  def __init__(self, brand, model, year):
    self.brand = brand
    self.model = model
    self.year = year

  def display_info(self):
    print(f"{self.year} {self.brand} {self.model}")

car1 = Car("Toyota", "Corolla", 2020)
car1.display_info()

class Person:
  def __init__(self, name):
    self.name = name

  def greet(self):
    return "Hello, " + self.name

  def welcome(self):
    message = self.greet()
    print(message + "! Welcome to our website.")

p1 = Person("Tobias")
p1.welcome()